In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
%load_ext autoreload
%autoreload 2

In [4]:
grid = np.load('rmse_lambda_K.npy')

In [7]:
min_error = grid[np.where(grid > 0)].min()

In [14]:
grid[0,:,:].min()

0.9822575004124746

In [15]:
grid[1,:,:].min()

0.9868347829975642

In [18]:
np.where(grid == min_error)

(array([0]), array([2]), array([1]))

In [22]:
np.where(grid == grid[2,:,:].min())

(array([2]), array([1]), array([2]))

In [13]:
min_error

0.9822575004124746

In [12]:
K = 10
lambda_u = 10**(-1)
lambda_i = 10**(-2)

In [17]:
grid[np.where(grid > 0)]

array([1.41649701, 1.04887978, 1.00732591, 1.0073203 , 1.05025272,
       1.00314847, 0.98341856, 1.00298601, 1.01079612, 0.9822575 ,
       1.00340499, 1.0106367 , 0.99957846, 0.98713585, 1.00463618,
       1.0111977 , 1.41649697, 1.04887974, 1.00725983, 1.0057545 ,
       1.05032496, 1.00464982, 0.98683478, 1.00636118, 1.0178259 ,
       1.00064828, 0.99859091, 1.02755764, 1.01796235, 1.00048298,
       1.00110583, 1.03026846, 1.416497  , 1.04887981, 1.00730398,
       1.00633894, 1.05034139, 1.00469751, 0.98335733, 0.99074928,
       1.01789071, 1.00118072, 0.98524449, 1.01561251, 1.01802633,
       1.00115253, 0.98680824, 1.02016566, 1.416497  , 1.04887978,
       1.00732583, 1.00676694, 1.05035273, 1.0047112 , 0.98391479])

In [25]:
np.copy([1,2])

array([1, 2])

In [50]:
np.round(1.5)

2.0

In [54]:
list(zip([1,2,3],[3,4,5]))

[(1, 3), (2, 4), (3, 5)]